# Build Stage
FROM node:18 AS builder

WORKDIR /app

# Copy files and install dependencies
COPY ./web/package.json ./web/package-lock.json ./
RUN npm install

COPY ./web .
RUN npm run build

# Serve Stage
FROM nginx:alpine

WORKDIR /usr/share/nginx/html

# Copy built files from the builder stage
COPY --from=builder /app/dist ./

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
